[phases.setup]
nixPkgs = ['python311']

[phases.install]
cmds = ['pip install --upgrade pip', 'pip install -r requirements.txt']

[start]
cmd = 'python manage.py migrate --noinput && python manage.py shell -c "from django.contrib.auth import get_user_model; User = get_user_model(); User.objects.filter(username=\"ukadmin\").exists() or User.objects.create_superuser(\"ukadmin\", \"admin@ukleatherjackets.com\", \"UKLeather2026!Shop\")" && python manage.py collectstatic --noinput && gunicorn leather_shop.wsgi:application --bind 0.0.0.0:$PORT'